### ISSUE TITLE
Community Building - Where do you hang digitally?

### ISSUE THREAD

**Issue by masud-abdulkadir** [thecore21m/thecore21m#1]
Curious as there wasn't a social link or anywhere to hang out as a digital community, curious if this project has any, such as telegram, discord or even Matrix Chat or Signal groups or anything really? :)

**Comment by masud-abdulkadir** [comment]
I found your linktree where you seem to have Telegram, Whatsapp, Facebook and Linkedin, where do you mostly hang out, and perhaps consider adding that link e.g. telegram to the github repo. Thanks in advance.

**Comment by thecore21m** [comment]
We hang mostly on WhatsApp, but the links are available. on our Git

**Comment by masud-abdulkadir** [comment]
Awesome, thanks!
